# Generated by Django 4.1.3 on 2022-12-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, verbose_name='روز')),
            ],
            options={
                'verbose_name': 'روز هفته',
                'verbose_name_plural': 'روزهای هفته',
            },
        ),
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.TimeField(verbose_name='ساعت کلاس')),
                ('WeekDay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.weekday')),
            ],
            options={
                'verbose_name': 'زمان امتحان',
                'verbose_name_plural': 'زمان های امتحان',
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='نام درس')),
                ('class_time', models.TimeField(verbose_name='ساعت کلاس')),
                ('even_odd_weeks', models.CharField(choices=[('even', 'زوج'), ('odd', 'فرد'), ('all', 'همه هفته ها')], default='all', max_length=4, verbose_name='هفته زوج یا فرد')),
                ('professor_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام استاد')),
                ('class_day', models.ManyToManyField(to='schedule.weekday', verbose_name='روز کلاس')),
                ('exam_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.examtime', verbose_name='زمان امتحان')),
            ],
            options={
                'verbose_name': 'برنامه کلاس',
                'verbose_name_plural': 'برنامه کلاس ها',
            },
        ),
    ]
