# Generated by Django 4.1.3 on 2022-12-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_classtime_class_day_alter_classtime_exam_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtime',
            name='exam_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time', to='schedule.weekday', verbose_name='روز امتحان'),
        ),
    ]
